version: '3'

services:
  bff:
    build:
      context: ./lesson4-bff
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - backend_host=backend:8080
  backend:
    build:
      context: ./lesson4-backend
      dockerfile: Dockerfile
