server:
  port: 8888

cloud:
  aws:
    credentials:
      profileName: profile juku
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error