cloud:
  aws:
    credentials:
      profileName:
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error